[[OpenAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9bcf046a70f503002b65de718dab128e9b39bf96"
libc = "glibc"
os = "linux"

    [[OpenAL.download]]
    sha256 = "a5ca3718a3cceea3c464ab65543efdc83b68233e93217df8a5e8194a006761b1"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.21.1+0/OpenAL.v1.21.1.i686-linux-gnu-cxx03.tar.gz"
[[OpenAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89cec1f02e05192b1806b6ee19cbe867b390d3c4"
libc = "glibc"
os = "linux"

    [[OpenAL.download]]
    sha256 = "5adc5a2aaa0068208466e71eb19891034d2b6c0307b5b080a4fcc78e73b0a819"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.21.1+0/OpenAL.v1.21.1.i686-linux-gnu-cxx11.tar.gz"
[[OpenAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2207742169baae1d5b2e4a55c20c502206f84feb"
libc = "musl"
os = "linux"

    [[OpenAL.download]]
    sha256 = "e0b7ebe06d111154fcd4bd37cea075ef78c06760bb37e7e9c1a44b4f0b92cbbb"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.21.1+0/OpenAL.v1.21.1.i686-linux-musl-cxx03.tar.gz"
[[OpenAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f887506a832341e30fa5633ab00d4dadab76655"
libc = "musl"
os = "linux"

    [[OpenAL.download]]
    sha256 = "29421e1fb17a9c2ed0c0fa9b09078c5e4d1e460c1c93bc21b6791cac6a70eccc"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.21.1+0/OpenAL.v1.21.1.i686-linux-musl-cxx11.tar.gz"
[[OpenAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6e576129b4880609bf3823f0b425a75c412ffc7"
libc = "glibc"
os = "linux"

    [[OpenAL.download]]
    sha256 = "4930484a2b3a0ab71c16c8cfc5f34123919af018ff42be5ebfcaf288ed40bc11"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.21.1+0/OpenAL.v1.21.1.x86_64-linux-gnu-cxx03.tar.gz"
[[OpenAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "394e9c0c61c8dd779e7afdc3505654dc85e5749d"
libc = "glibc"
os = "linux"

    [[OpenAL.download]]
    sha256 = "7e828d94f27cd6da4862dd666740775a34f67b2f1ec5039b6db524c8f278e987"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.21.1+0/OpenAL.v1.21.1.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61cde6cc32a06f82bc6d07ba13f0a4c2fad1cc3e"
libc = "musl"
os = "linux"

    [[OpenAL.download]]
    sha256 = "8f590b2df4b0e403ccd5665e7d23b8aacd92e5f2b42fc3c5c52fe2b0f4b80a79"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.21.1+0/OpenAL.v1.21.1.x86_64-linux-musl-cxx03.tar.gz"
[[OpenAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81ebb54bca4209bc20b6bd5d6b7d453c49acaeee"
libc = "musl"
os = "linux"

    [[OpenAL.download]]
    sha256 = "7365595d7d97d38101a05eaf13da2751c3abaf40fd924b1e0f12abe1a4e26b78"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.21.1+0/OpenAL.v1.21.1.x86_64-linux-musl-cxx11.tar.gz"
