[[OpenAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96c0babaff075ac1810e1b4a59b127baef901fe5"
libc = "glibc"
os = "linux"

    [[OpenAL.download]]
    sha256 = "1f02892ad49619afaedb2e1dd3c910a649b3fd4d606c1d3ddebc6685d396f907"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.19.0+0/OpenAL.v1.19.0.i686-linux-gnu-cxx03.tar.gz"
[[OpenAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b57b8f5fd736cc89a9f1d7225522de94d4771a75"
libc = "glibc"
os = "linux"

    [[OpenAL.download]]
    sha256 = "e6367143c816bedd2c59ed389c7269cc3a2ec8bb6784e1ebb9bc199558fb2847"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.19.0+0/OpenAL.v1.19.0.i686-linux-gnu-cxx11.tar.gz"
[[OpenAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eeb633a14092920bc9ccb5a226c91cad57cd281b"
libc = "musl"
os = "linux"

    [[OpenAL.download]]
    sha256 = "b3f7c1c2495058aa3aed87d66d3e0248597d53239c994c2bd6bbeebfde8ddb25"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.19.0+0/OpenAL.v1.19.0.i686-linux-musl-cxx03.tar.gz"
[[OpenAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49150e7f03b6a389ffad44484265b9bdf9bc1fce"
libc = "musl"
os = "linux"

    [[OpenAL.download]]
    sha256 = "d661a6e218e70a761143360ef81797d220e1b8af3e828e84f28ceee8ca16d06a"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.19.0+0/OpenAL.v1.19.0.i686-linux-musl-cxx11.tar.gz"
[[OpenAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ce58a5159890b41656110a9d07ab7d135af8901"
libc = "glibc"
os = "linux"

    [[OpenAL.download]]
    sha256 = "73c664408e494a58b4f7beb38bca8dcb85dec674135e6bd38002fe3a5abb1520"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.19.0+0/OpenAL.v1.19.0.x86_64-linux-gnu-cxx03.tar.gz"
[[OpenAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f47927d5575b220bcc0e337fa3857aded6bc7419"
libc = "glibc"
os = "linux"

    [[OpenAL.download]]
    sha256 = "533aaf93f8a0fd7affd5ddf380e4603c594e39138d5b36a35bc9476b04d27b01"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.19.0+0/OpenAL.v1.19.0.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d60d96d81e8d979b1985106395acfbdb6727746"
libc = "musl"
os = "linux"

    [[OpenAL.download]]
    sha256 = "6b99d830eabdec614d0c00e690e70ae836f34317dfee44602e93ea9cabc500d7"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.19.0+0/OpenAL.v1.19.0.x86_64-linux-musl-cxx03.tar.gz"
[[OpenAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32c8316f392461be03526d6b1813d3ff0ad7c723"
libc = "musl"
os = "linux"

    [[OpenAL.download]]
    sha256 = "ddd6429a7b1220d0dd2d562798dc586d1983e5b011bb97d0c9bdf34f700c3e9d"
    url = "https://github.com/JuliaBinaryWrappers/OpenAL_jll.jl/releases/download/OpenAL-v1.19.0+0/OpenAL.v1.19.0.x86_64-linux-musl-cxx11.tar.gz"
